name: build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Detekt
      run: ./gradlew detekt

    - name: Build with Gradle
      run: ./gradlew lib:build

    - name: unit tests
      run: ./gradlew testDebugUnitTest

    - name: Upload artifact on tests failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: Unit test report
        path: '**/build/reports/tests/**'

    - name: Coverage report
      run: ./gradlew jacocoTestCoverageVerification

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: UI Tests report
        path: '**/app/build/reports/jacoco/**'

    - name: Log success message
      run: echo "Build finished successfully"
